'    Copyright (C) 2018-2026 Hazel Ward
'
'    This file is a part of Winapp2ool
'
'    Winapp2ool is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 3 of the License, or
'    (at your option) any later version.
'
'    Winapp2ool is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.
'
'    You should have received a copy of the GNU General Public License
'    along with Winapp2ool.  If not, see <http://www.gnu.org/licenses/>.

Option Strict On

Friend Module BrowserEntryGenerator

    ''' <summary>
    ''' Produces entries for the Opera GX browser by transforming the EntryScaffold template
    ''' paths in accordance with the non-standard way Opera GX stores itself on the disk by default
    ''' </summary>
    '''
    ''' <param name="browserName">
    ''' The name of the browser being processed
    ''' </param>
    '''
    ''' <param name="fileKeyBase">
    ''' A FileKey template to be transformed such that it is appropriate for Opera GX
    ''' </param>
    '''
    ''' <param name="fileKeyNum">
    ''' The number of the current FileKey being generated
    ''' </param>
    '''
    ''' <param name="newSection">
    ''' The <c>iniSection2</c> currently being generated by Browser Builder
    ''' </param>
    '''
    ''' <param name="userDataPath">
    ''' The resolved <c>%UserDataPath%</c> value for the current browser, provided by its
    ''' <c>BrowserInfo</c> section
    ''' </param>
    '''
    ''' <returns>
    ''' <see langword="True"/> if the current browser is Opera GX and FileKeys were generated;
    ''' <see langword="False"/> if the browser is not Opera GX or the path pattern is unsupported
    ''' </returns>
    Private Function processOperaGX(browserName As String,
                                    fileKeyBase As String,
                              ByRef fileKeyNum As Integer,
                              ByRef newSection As iniSection2,
                                    userDataPath As String) As Boolean

        If Not browserName.Equals("Opera GX") Then Return False

        Dim baseKeyValue As String
        Dim sideProfileKeyValue As String

        ' Opera GX stores files both in the main user data directory (without a folder such as Default)
        ' and any profiles created in _side_profiles\* subdirectories instead of the usual Profile1, etc.
        ' Accordingly, we transform our scaffold templates to accommodate this
        ' %UserDataPath%\*|<params> -> %UserDataPath%|<params> + %UserDataPath%\_side_profiles\*|<params>
        ' %UserDataPath%\*\<directory> -> %UserDataPath%\<directory> + %UserDataPath%\_side_profiles\*\<directory>
        ' %UserDataPath%|<params> -> %UserDataPath%|<params> + %UserDataPath%\_side_profiles\*|<params>
        ' %UserDataPath%\<directory> -> %UserDataPath%\<directory> + %UserDataPath%\_side_profiles\*\<directory>

        Select Case True

            '%UserDataPath%\*|<params> -> remove \* + create side profiles variant
            Case fileKeyBase.StartsWith("%UserDataPath%\*|")

                Dim afterWildcardPipe As String = fileKeyBase.Substring("%UserDataPath%\*|".Length)
                baseKeyValue = userDataPath & "|" & afterWildcardPipe
                sideProfileKeyValue = userDataPath & "\_side_profiles\*|" & afterWildcardPipe

            ' %UserDataPath%\*\<directory> -> unnest one level + create side profiles variant
            Case fileKeyBase.StartsWith("%UserDataPath%\*\")

                Dim afterWildcard As String = fileKeyBase.Substring("%UserDataPath%\*\".Length)
                baseKeyValue = userDataPath & "\" & afterWildcard
                sideProfileKeyValue = userDataPath & "\_side_profiles\*\" & afterWildcard

            ' %UserDataPath%|<params> -> keep + create side profiles variant
            Case fileKeyBase.StartsWith("%UserDataPath%|")

                Dim afterPipe As String = fileKeyBase.Substring("%UserDataPath%|".Length)
                baseKeyValue = userDataPath & "|" & afterPipe
                sideProfileKeyValue = userDataPath & "\_side_profiles\*|" & afterPipe

            ' %UserDataPath%\<directory> -> (non-wildcard subdirectory - RETAINS wildcards in directory names)
            Case fileKeyBase.StartsWith("%UserDataPath%\")

                Dim afterBackslash As String = fileKeyBase.Substring("%UserDataPath%\".Length)
                baseKeyValue = userDataPath & "\" & afterBackslash
                sideProfileKeyValue = userDataPath & "\_side_profiles\*\" & afterBackslash

            Case Else

                Dim errMsg = $"Unsupported OperaGX path provided in {fileKeyBase}"
                gLog(errMsg)
                Return False

        End Select

        CreateAndAddKey(newSection, "FileKey", fileKeyNum, baseKeyValue)
        CreateAndAddKey(newSection, "FileKey", fileKeyNum, sideProfileKeyValue)

        Return True

    End Function

    ''' <summary>
    ''' Generates a browser entry using pre-computed browser information
    ''' </summary>
    '''
    ''' <param name="browserInfo">
    ''' Pre-computed <c>BrowserInfo</c> structure containing all browser parameters
    ''' </param>
    '''
    ''' <param name="scaffoldName">
    ''' The name of the <c>EntryScaffold</c> used as a template for the current entry being generated
    ''' </param>
    '''
    ''' <param name="fileKeyBases">
    ''' A set of FileKey templates that will be personalized for the current browser
    ''' </param>
    '''
    ''' <param name="regKeyBases">
    ''' A set of RegKey templates that will be personalized for the current browser
    ''' </param>
    '''
    ''' <param name="outputFile">
    ''' The <c>iniFile2</c> containing all the entries being generated by Browser Builder
    ''' </param>
    '''
    ''' <param name="isGecko">
    ''' Indicates whether or not the Browser being processed is a Gecko-based browser
    ''' </param>
    '''
    ''' <param name="menuOutput">
    ''' The <c>MenuSection</c> accumulating user-visible output for this run
    ''' </param>
    Friend Sub generateBrowserEntry(browserInfo As BrowserInfo,
                                    scaffoldName As String,
                                    fileKeyBases As List(Of String),
                                    regKeyBases As List(Of String),
                              ByRef outputFile As iniFile2,
                                    isGecko As Boolean,
                              ByRef menuOutput As MenuSection)

        Dim generatingMsg = $"Generating entry for browser: {browserInfo.Name}"
        gLog(generatingMsg, indent:=True)
        menuOutput.AddColoredLine(generatingMsg, ConsoleColor.Magenta)

        Dim entryName As String = $"{browserInfo.Name} {scaffoldName} *"
        Dim newSection As New iniSection2(entryName)
        newSection.AddKey(New iniKey2($"Section={browserInfo.SectionName}"))

        processUserDataPaths(newSection, browserInfo.UserDataPaths, browserInfo.UserDataParentPaths, browserInfo.TruncateDetect, fileKeyBases, browserInfo.Name, isGecko)

        processRegKeyBases(regKeyBases, newSection, browserInfo.RegistryRoots)

        outputFile.AddSection(newSection)

        Dim generatedText = $"Generated entry: {entryName}"
        menuOutput.AddColoredLine(generatedText, ConsoleColor.Yellow)
        gLog(generatedText, indent:=True, indAmt:=4)

    End Sub

    ''' <summary>
    ''' Generates any necessary RegKey entries based on the provided RegKeyBases
    ''' and adds them into <paramref name="newSection"/>
    ''' </summary>
    '''
    ''' <param name="regKeyBases">
    ''' The set of templates for RegKeys that will be personalized for the current browser
    ''' </param>
    '''
    ''' <param name="newSection">
    ''' The <c>iniSection2</c> to which the generated RegKeys will be added
    ''' </param>
    '''
    ''' <param name="RegistryRoots">
    ''' The set of root paths in the registry for the current browser's RegKeys
    ''' </param>
    Private Sub processRegKeyBases(regKeyBases As List(Of String),
                             ByRef newSection As iniSection2,
                                   RegistryRoots As List(Of String))

        Dim regKeyNum As Integer = 1

        For Each regKeyBase In regKeyBases

            For Each root In RegistryRoots

                CreateAndAddKey(newSection, "RegKey", regKeyNum, regKeyBase.Replace("%RegistryRoot%", root))

            Next

        Next

    End Sub

    ''' <summary>
    ''' Creates a numbered <c>iniKey2</c> with the provided <paramref name="keyName"/>,
    ''' <paramref name="keyNum"/>, and <paramref name="keyValue"/>, then adds it to
    ''' <paramref name="section"/>, incrementing <paramref name="keyNum"/>
    ''' </summary>
    '''
    ''' <param name="section">
    ''' An <c>iniSection2</c> to which a key will be added
    ''' </param>
    '''
    ''' <param name="keyName">
    ''' The name of the key, does not include numbers
    ''' </param>
    '''
    ''' <param name="keyNum">
    ''' The number appended after <paramref name="keyName"/>
    ''' </param>
    '''
    ''' <param name="keyValue">
    ''' The value of the key
    ''' </param>
    Private Sub CreateAndAddKey(ByRef section As iniSection2,
                                      keyName As String,
                                ByRef keyNum As Integer,
                                      keyValue As String)

        section.AddKey(New iniKey2($"{keyName}{keyNum}={keyValue}"))
        keyNum += 1

    End Sub

    ''' <summary>
    ''' Iterates through the user data paths and generates DetectFile and FileKey entries
    ''' for each path, adding them to <paramref name="newSection"/>
    ''' </summary>
    '''
    ''' <param name="newSection">
    ''' The <c>iniSection2</c> currently being built by Browser Builder
    ''' </param>
    '''
    ''' <param name="userDataPaths">
    ''' The set of user data paths provided from the ruleset file for the current browser
    ''' </param>
    '''
    ''' <param name="userDataParentPaths">
    ''' The set of parent paths for the user data paths, used for truncation
    ''' </param>
    '''
    ''' <param name="truncate">
    ''' Indicates that the parent path should be used instead of the user data path for the purpose
    ''' of creating DetectFile keys
    ''' </param>
    '''
    ''' <param name="fileKeyBases">
    ''' The set of FileKey templates provided by the current <c>EntryScaffold</c>
    ''' </param>
    '''
    ''' <param name="BrowserName">
    ''' The name of the browser for which the current entry is being built
    ''' </param>
    '''
    ''' <param name="isGecko">
    ''' Indicates whether or not the current browser is gecko-based
    ''' </param>
    Private Sub processUserDataPaths(ByRef newSection As iniSection2,
                                     ByRef userDataPaths As List(Of String),
                                     ByRef userDataParentPaths As List(Of String),
                                           truncate As Boolean,
                                     ByRef fileKeyBases As List(Of String),
                                           BrowserName As String,
                                           isGecko As Boolean)

        Dim fileKeyNum As Integer = 1
        Dim multiPath = userDataPaths.Count > 1

        For i = 0 To userDataPaths.Count - 1

            Dim DetectFileNum = If(multiPath, (i + 1).ToString, "")
            newSection.AddKey(New iniKey2($"DetectFile{DetectFileNum}={If(truncate, userDataParentPaths(i), userDataPaths(i))}"))

            For Each fileKeyBase In fileKeyBases

                Dim fileKeyValue As String

                Select Case True

                    Case fileKeyBase.Contains("%UserDataPath%")

                        If processOperaGX(BrowserName, fileKeyBase, fileKeyNum, newSection, userDataPaths(i)) Then Continue For

                        fileKeyValue = fileKeyBase.Replace("%UserDataPath%", userDataPaths(i))

                    Case fileKeyBase.Contains("%BrowserPath%")

                        fileKeyValue = fileKeyBase.Replace("%BrowserPath%", userDataParentPaths(i))

                        If isGecko Then Exit Select

                        Dim fileKeyValue2 = fileKeyValue.Replace("%LocalAppData%", "%ProgramFiles%")
                        fileKeyValue2 = fileKeyValue2.Replace("%AppData%", "%ProgramFiles%")
                        CreateAndAddKey(newSection, "FileKey", fileKeyNum, fileKeyValue2)

                    Case fileKeyBase.Contains("%LocalDataPath%") AndAlso isGecko

                        Dim localdatapath = userDataPaths(i).Replace("%AppData%", "%LocalAppData%")
                        fileKeyValue = fileKeyBase.Replace("%LocalDataPath%", localdatapath)

                    Case Else : Continue For

                End Select

                CreateAndAddKey(newSection, "FileKey", fileKeyNum, fileKeyValue)

            Next

        Next

    End Sub

End Module
