#!/usr/bin/env bash
#
# Generated-artifact guard: did this change edit a BUILD OUTPUT without editing the
# SOURCE that produces it?
#
# Every .ini under Assembler/Entries/, plus the seven published Winapp2.ini/diff.txt
# pairs, is generated by `Assembler/build winapp2.ps1`. Hand-editing one of them looks
# like it worked, the file on disk says what you wanted, and then the next daily
# build regenerates it from the untouched source and silently reverts the edit. The
# change does not fail, it evaporates, and it evaporates in tomorrow's changelog rather
# than in CI today. This script turns that class of mistake into a red X immediately.
#
# It is a *provenance* check, not a correctness check: it never runs winapp2ool and never
# compares content. It only asks whether the set of changed paths is coherent. The
# companion artifact-drift.yml answers the harder question (does the committed output
# still match what the generators actually produce).
#
# Two rules, both hard failures:
#
#   1. Aggregate. If any generated file changed and NO build source changed at all, the
#      change is pure hand-editing of output. This is the common oopsie: edit
#      Assembler/Entries/#.ini when you meant Assembler/EntryBuilder/#.ini.
#
#   2. Per-artifact. Each generated artifact names the source directory that feeds it:
#        Assembler/Entries/<L>.ini      <- Assembler/EntryBuilder/<L>.ini   (1:1 by letter)
#        Assembler/Entries/Browsers/*   <- Assembler/BrowserBuilder/**
#        Assembler/Entries/UWP/*        <- Assembler/UWP/**
#      A changed artifact whose own source is untouched is flagged even when some
#      unrelated source changed -- that catches "correct source edit, plus a stray
#      hand-edit somewhere else in Entries/."
#      Rule 2 is SUPPRESSED when a global input changed (see GLOBAL below), because
#      those legitimately ripple into artifacts whose per-letter source is untouched.
#
# The aggregate published files (Winapp2.ini, Non-CCleaner/**) are deliberately only
# covered by rule 1: any source anywhere can legitimately move them, so there is no
# narrower source to demand.
#
# KNOWN LIMITATION -- rule 1 cannot tell a hand-edit from a deliberate regeneration.
# "Output moved, source did not" has two innocent causes besides the oopsie: seeding a
# brand-new artifact for the first time, and committing a regeneration to repair drift
# that some earlier change introduced (an exe rebuild, say). Both are output-only commits
# and both trip rule 1. Distinguishing them would require actually running the build,
# which is artifact-drift.yml's job and costs minutes on a Windows runner; this check
# costs seconds and looks only at path names. So the innocent cases declare themselves:
# put [regen] (or [skip-generated-check]) in the commit message or PR title.
#
# Historical calibration: over the 120 commits before 2026-07-28, five human commits
# touched generated files. One was clean, two were drift regenerations, two were
# first-time artifact seeding -- so expect this to want the token a few times a year,
# almost always on a commit whose message already says "regenerate". Rule 2 flagged none
# of the five: it has no known false-positive class.
#
# Usage:
#   check-generated-sources.sh <base-ref> <head-ref>   # diff two refs
#   check-generated-sources.sh --files <path>          # read a newline-separated list
#                                                     # (for local testing)
# Exit 0 = coherent, 1 = incoherent, 2 = bad invocation.

set -uo pipefail

# ---------------------------------------------------------------- collect changed paths

changed_list=""

if [ "${1:-}" = "--files" ]; then
  [ -n "${2:-}" ] && [ -f "$2" ] || { echo "usage: $0 --files <path>" >&2; exit 2; }
  changed_list=$(cat -- "$2")
elif [ -n "${1:-}" ] && [ -n "${2:-}" ]; then
  # Three-dot: what the head added relative to the merge base, so unrelated commits
  # that landed on the base branch meanwhile are not attributed to this change.
  changed_list=$(git diff --name-only "$1...$2" --) || {
    echo "error: git diff $1...$2 failed" >&2; exit 2; }
else
  echo "usage: $0 <base-ref> <head-ref> | $0 --files <path>" >&2
  exit 2
fi

if [ -z "$changed_list" ]; then
  echo "No changed files; nothing to check."
  exit 0
fi

# ---------------------------------------------------------------------------- classify

# Generated artifacts touched, split by kind.
gen_letters=""      # bare letters, e.g. "A M #"
gen_browsers=0
gen_uwp=0
gen_other=""        # other Entries/ files + the published aggregates
gen_count=0

# Build inputs touched.
src_count=0
src_entrybuilder=""     # bare letters whose EntryBuilder source changed
src_browserbuilder=0
src_uwp=0
global=0                # a global input changed -> suppress rule 2
global_why=""

while IFS= read -r f; do
  [ -n "$f" ] || continue

  case "$f" in
    # Docs never affect the build.
    *.md) continue ;;

    # ---- global inputs: these can change any artifact's content on their own.
    'Assembler/Scaffolds/'*)
      src_count=$((src_count + 1)); global=1
      global_why="${global_why}${global_why:+, }shared scaffold catalogs"
      continue ;;
    'Assembler/winapp2ool.exe')
      src_count=$((src_count + 1)); global=1
      global_why="${global_why}${global_why:+, }the committed winapp2ool.exe"
      continue ;;
    'Assembler/build winapp2.ps1')
      src_count=$((src_count + 1)); global=1
      global_why="${global_why}${global_why:+, }the build script"
      continue ;;
    'winapp2ool/'*)
      src_count=$((src_count + 1)); global=1
      global_why="${global_why}${global_why:+, }winapp2ool source"
      continue ;;

    # ---- generated artifacts.
    'Assembler/Entries/Browsers/'*) gen_browsers=1; gen_count=$((gen_count + 1)) ;;
    'Assembler/Entries/UWP/'*)      gen_uwp=1;      gen_count=$((gen_count + 1)) ;;
    'Assembler/Entries/'*.ini)
      base=${f##*/}; letter=${base%.ini}
      gen_count=$((gen_count + 1))
      case "$letter" in
        # Exactly the 27 buckets EntryBuilder -split writes. Anything else under
        # Entries/ is not a per-letter artifact; fall through to gen_other.
        '#'|[A-Z]) gen_letters="$gen_letters $letter" ;;
        *)         gen_other="$gen_other $f" ;;
      esac ;;
    'Assembler/Entries/'*)
      gen_count=$((gen_count + 1)); gen_other="$gen_other $f" ;;
    'Winapp2.ini'|'diff.txt'|'Non-CCleaner/'*'Winapp2.ini'|'Non-CCleaner/'*'Winapp2.rules'|'Non-CCleaner/'*'diff.txt')
      gen_count=$((gen_count + 1)); gen_other="$gen_other $f" ;;

    # ---- per-artifact sources.
    'Assembler/EntryBuilder/'*.ini)
      src_count=$((src_count + 1))
      base=${f##*/}
      src_entrybuilder="$src_entrybuilder ${base%.ini}" ;;
    'Assembler/BrowserBuilder/'*)
      src_count=$((src_count + 1)); src_browserbuilder=1 ;;
    'Assembler/UWP/'*)
      src_count=$((src_count + 1)); src_uwp=1 ;;

    # ---- anything else under Assembler/ is a build input: flavor Transmute
    # directories, EntryBuilder files that are not .ini, future generator sources.
    # Default-source (rather than an explicit allowlist) means adding a new flavor
    # or generator source dir does not need an edit here to avoid a false failure.
    'Assembler/'*)
      src_count=$((src_count + 1)) ;;
  esac
done <<EOF
$changed_list
EOF

if [ "$gen_count" -eq 0 ]; then
  echo "No generated artifacts changed; nothing to check."
  exit 0
fi

# ------------------------------------------------------------------------------ verdict

# Emitted as GitHub annotations when running in Actions, plain text otherwise.
fail=0
summary=""

note() { summary="${summary}$1
"; }

annotate() {
  # annotate <file> <message>
  if [ -n "${GITHUB_ACTIONS:-}" ]; then
    echo "::error file=$1::$2"
  else
    echo "error: $1: $2"
  fi
}

if [ "$src_count" -eq 0 ]; then
  # Rule 1.
  fail=1
  note "**$gen_count generated file(s) changed, and no build source changed.**"
  note ""
  note "If this was meant to be a content change: these files are build output. The next"
  note "build regenerates them from their sources and will silently discard the edit."
  note "Make it in the source instead -- mapping below."
  note ""
  note "If you deliberately committed regenerated output (repairing drift, or seeding a"
  note "new artifact), that is fine and this check cannot tell the difference -- add"
  note "\`[regen]\` to the commit message or PR title."
  for letter in $gen_letters; do
    annotate "Assembler/Entries/$letter.ini" \
      "generated by EntryBuilder -- edit Assembler/EntryBuilder/$letter.ini instead"
    note "- \`Assembler/Entries/$letter.ini\` <- \`Assembler/EntryBuilder/$letter.ini\`"
  done
  if [ "$gen_browsers" -eq 1 ]; then
    annotate "Assembler/Entries/Browsers/browsers.ini" \
      "generated by BrowserBuilder -- edit the sources in Assembler/BrowserBuilder/ instead"
    note "- \`Assembler/Entries/Browsers/browsers.ini\` <- \`Assembler/BrowserBuilder/\`"
  fi
  if [ "$gen_uwp" -eq 1 ]; then
    annotate "Assembler/Entries/UWP/uwp.ini" \
      "generated by UWPBuilder -- edit the sources in Assembler/UWP/ instead"
    note "- \`Assembler/Entries/UWP/uwp.ini\` <- \`Assembler/UWP/\`"
  fi
  for f in $gen_other; do
    annotate "$f" "build output -- edit the sources under Assembler/ instead"
    note "- \`$f\` <- the build (\`Assembler/build winapp2.ps1\`)"
  done

elif [ "$global" -eq 1 ]; then
  # Rule 2 suppressed: a global input legitimately ripples into artifacts whose own
  # per-letter source is untouched.
  echo "Build sources changed, including a global input ($global_why)."
  echo "Skipping the per-artifact source check -- a global input can change any artifact."

else
  # Rule 2.
  orphans=""
  for letter in $gen_letters; do
    matched=0
    for s in $src_entrybuilder; do
      [ "$s" = "$letter" ] && { matched=1; break; }
    done
    if [ "$matched" -eq 0 ]; then
      fail=1
      orphans=1
      annotate "Assembler/Entries/$letter.ini" \
        "changed, but its source Assembler/EntryBuilder/$letter.ini did not -- this edit will be regenerated away"
      note "- \`Assembler/Entries/$letter.ini\` changed, but \`Assembler/EntryBuilder/$letter.ini\` did not"
    fi
  done
  if [ "$gen_browsers" -eq 1 ] && [ "$src_browserbuilder" -eq 0 ]; then
    fail=1; orphans=1
    annotate "Assembler/Entries/Browsers/browsers.ini" \
      "changed, but no source under Assembler/BrowserBuilder/ did -- this edit will be regenerated away"
    note "- \`Assembler/Entries/Browsers/browsers.ini\` changed, but nothing under \`Assembler/BrowserBuilder/\` did"
  fi
  if [ "$gen_uwp" -eq 1 ] && [ "$src_uwp" -eq 0 ]; then
    fail=1; orphans=1
    annotate "Assembler/Entries/UWP/uwp.ini" \
      "changed, but no source under Assembler/UWP/ did -- this edit will be regenerated away"
    note "- \`Assembler/Entries/UWP/uwp.ini\` changed, but nothing under \`Assembler/UWP/\` did"
  fi

  if [ -n "$orphans" ]; then
    note ""
    note "Each artifact above is regenerated from the source next to it. A generated"
    note "file that moves without its source is a hand-edit, and the next build reverts it."
  fi
fi

# ------------------------------------------------------------------------------- report

if [ "$fail" -eq 0 ]; then
  echo "OK: $gen_count generated file(s) changed, and their sources changed too."
  if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
    {
      echo "### Generated-artifact guard: pass"
      echo
      echo "$gen_count generated file(s) changed alongside their build sources."
    } >> "$GITHUB_STEP_SUMMARY"
  fi
  exit 0
fi

if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  {
    echo "### Generated-artifact guard: fail"
    echo
    printf '%s' "$summary"
    echo
    echo "Everything under \`Assembler/Entries/\`, the seven published \`Winapp2.ini\`"
    echo "files, and every \`diff.txt\` are **build output**, produced by"
    echo "\`Assembler/build winapp2.ps1\`. Edit the sources; let the build write the output."
    echo
    echo "To override -- committing regenerated output on purpose is the usual reason --"
    echo "put \`[regen]\` or \`[skip-generated-check]\` in the commit message or PR title."
  } >> "$GITHUB_STEP_SUMMARY"
fi

echo
printf '%s' "$summary" | sed 's/^/  /'
echo
echo "Generated-artifact guard FAILED. Edit sources, not build output."
exit 1
