'    Copyright (C) 2018-2026 Hazel Ward
' 
'    This file is a part of Winapp2ool
' 
'    Winapp2ool is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 3 of the License, or
'    (at your option) any later version.
'
'    Winapp2ool is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.
'
'    You should have received a copy of the GNU General Public License
'    along with Winapp2ool.  If not, see <http://www.gnu.org/licenses/>.

Option Strict On

''' <summary>
''' Shared constants and lookup tables used across
''' the Diff module's detection and comparison logic
''' </summary>
Public Module DiffConfiguration

    ''' <summary>
    ''' Deprecated variables and patterns mapped to the forms that replaced them.
    ''' <see cref="EntryChangeDetector.SnuffNoisyChanges"/> rewrites every key value in both files
    ''' with these before comparing, so an old file that still uses a deprecated form doesn't show
    ''' each key that uses it as changed. The rewrite is a case-sensitive <c> String.Replace </c>.
    ''' </summary>
    Public ReadOnly Property PathReplacements As New Dictionary(Of String, String) From {
        {"%CommonAppData%", "%ProgramData%"},
        {"%LocalLowAppData%", "%UserProfile%\AppData\LocalLow"},
        {"*.*", "*"}, {"%Pictures%", "%UserProfile%\Pictures"},
        {"%Videos%", "%UserProfile%\Videos"},
        {"%Music%", "%UserProfile%\Music"},
        {"%Documents%", "%UserProfile%\Documents"}
    }

    ''' <summary>
    ''' File system and registry locations too vague to show on their own that two entries share
    ''' content. Rename and merge detection doesn't count a key as matched when the old key's
    ''' value, or a fuzzy-matched new key's path, is exactly one of these (case-sensitive).
    ''' </summary>

    Public ReadOnly Property DisallowedPaths As New HashSet(Of String) From {
                "%Documents%\Add-in Express", "%UserProfile%\Desktop", "%LocalAppData%",
                "%WinDir%\System32", "%SystemDrive%", "%WinDir%", "%UserProfile%", "%Documents%",
                "%CommonAppData%", "%AppData%", "%Pictures%", "%Public%", "%Music%", "%Video%",
                "HKCU\Software\Microsoft\Windows", "HKLM\Software\Microsoft\Windows",
                "HKCU\Software\Microsoft\VisualStudio", "%LocalAppData%\Microsoft\Edge*",
                "HKCU\Software\Opera Software", "HKCU\Software\Vivaldi", "HKCU\Software\BraveSoftware",
                "%LocalAppData%\Packages\*\AC\Microsoft\CLR_v4.0*"
    }

    ''' <summary>
    ''' Key types left out whenever Diff compares an old key list against a new one, so they never
    ''' count as added, removed or updated. They carry nothing the entry name doesn't.
    ''' <br /> <br />
    ''' Currently: <c> ID </c> (CCleaner 7 format, duplicates the section name)
    ''' </summary>
    Public ReadOnly Property IgnoredKeyTypes As New HashSet(Of String)(StringComparer.OrdinalIgnoreCase) From {
        "ID"
    }

    ''' <summary>
    ''' Key types that classify an entry into a category.
    ''' At most one of these should appear per entry, so when
    ''' the old and new key both belong to this set they are
    ''' treated as an update rather than a remove + add.
    ''' <br /> <br />
    ''' <c> LangSecRef </c> and <c> Section </c> are the base format classifiers;
    ''' <c> Tags </c> is the CCleaner 7 equivalent.
    ''' </summary>
    Public ReadOnly Property ClassifierKeyTypes As String() = {"LangSecRef", "Section", "Tags"}

    ''' <summary>
    ''' Key types that make up an entry's detection criteria: how winapp2ool decides the target
    ''' application is present. We treat them as one role even when an entry mixes types, so a lone
    ''' removed <c> Detect </c> and a lone added <c> DetectFile </c> pair up as a modification
    ''' rather than a remove and an add, and the output itemizes their updates under one label.
    ''' <br /> <br />
    ''' Excludes <c> DetectOS </c> (an OS-version gate, handled as a defunct singleton) and
    ''' <c> SpecialDetect </c> (deprecated).
    ''' </summary>
    Public ReadOnly Property DetectionKeyTypes As New HashSet(Of String)(StringComparer.OrdinalIgnoreCase) From {
        "Detect", "DetectFile"
    }

    ''' <summary>
    ''' Substring matched (case-insensitive) against <c> Section </c> key values
    ''' to identify web browser entries generated by BrowserBuilder
    ''' </summary>
    Public Const BrowserSectionSubstring As String = "Web Browser"

    ''' <summary>
    ''' LangSecRef values associated with web browsers
    ''' </summary>
    Public ReadOnly Property BrowserSecRefs As String() = {
        "3029", "3006", "3033", "3034", "3027", "3026", "3030", "3001"
    }

    ''' <summary>
    ''' Separator used in the movement signatures that key <see cref="KeyMovementTracker.MovedKeys"/>.
    ''' We use <c> Chr(0) </c> because winapp2.ini key names and values don't contain it.
    ''' </summary>
    Public ReadOnly Property MovementKeySeparator As Char

        Get

            Return Chr(0)

        End Get

    End Property

End Module
