; This file is part of winapp2ool. If you are looking for winapp2.ini, please follow the link in line 6
;
; Winapp2.ini is fully licensed under the CC-BY-SA-4.0 license agreement. Please refer to our license agreement before using Winapp2.ini: https://github.com/MoscaDotTo/Winapp2/blob/master/License.md
; You may copy, modify, remix, share, show, and transmit Winapp2 but you must redistribute under the same license and you must attribute the original work to the winapp2 project
;
; You can get the latest Winapp2.ini here: https://github.com/MoscaDotTo/Winapp2
; Any contributions are appreciated. Please refer to our ReadMe to learn to make your own entries here: https://github.com/MoscaDotTo/Winapp2/blob/master/README.md
;
; Try out Winapp2ool for many useful additional features including updating and trimming Winapp2.ini: https://github.com/MoscaDotTo/Winapp2/raw/master/winapp2ool/bin/Release/winapp2ool.exe
; You can find the Winapp2ool ReadMe here: https://github.com/MoscaDotTo/Winapp2/blob/master/winapp2ool/Readme.md
;
; This file contains winapp2.ini entries beginning with the letter A and will be assembled by winapp2ool into the final winapp2.ini file

[Active@ File Recovery *]
LangSecRef=3024
Detect=HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\{C34F36E0-4D8B-42E8-90AD-50C76E1AE282}_is1
FileKey1=%ProgramFiles%\LSoft Technologies\Active@ File Recovery*|*Log.txt;*.scn;*.xml

[Active@ KillDisk *]
LangSecRef=3024
Detect=HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\{0F62EFB8-3C1C-4EE6-B6EF-9593007F9B03}_is1
FileKey1=%ProgramFiles%\LSoft Technologies\Active@ KillDisk*|*.log;*.xml

[AIDA64 *]
LangSecRef=3021
Detect=HKCU\Software\FinalWire\AIDA64
FileKey1=%UserProfile%\Documents\AIDA64 Reports|*|REMOVESELF

[Aimersoft *]
LangSecRef=3023
Detect=HKLM\Software\Aimersoft
FileKey1=%ProgramData%\Aimersoft\*\*Logs|*|RECURSE
FileKey2=%Public%\Documents\Aimersoft|*|REMOVESELF

[Aiseesoft Burnova *]
LangSecRef=3021
DetectFile=%ProgramData%\Aiseesoft Studio\Burnova
FileKey1=%UserProfile%\Documents\Log Files|dvdcore*.log

[All Zombies Must Die! *]
Section=Games
Detect=HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\All Zombies Must Die!_is1
FileKey1=%ProgramFiles%\Doublesix Games\All Zombies Must Die!\Prerequisites|*|REMOVESELF
FileKey2=%UserProfile%\Documents\My Games\UnrealEngine3\Bzb2Game\Logs|*

[Android Studio *]
LangSecRef=3021
Detect=HKCU\Software\Android Open Source Project\Emulator
FileKey1=%UserProfile%\.AndroidStudio2.3\system\log|*|REMOVESELF
FileKey2=%UserProfile%\.AndroidStudio2.3\system\tmp|*
FileKey3=%UserProfile%\.gradle|*.log|RECURSE

[Ashampoo ActionCam *]
LangSecRef=3024
DetectFile=%AppData%\Ashampoo\Ashampoo ActionCam
FileKey1=%UserProfile%\Documents|Ashampoo ActionCam.tmp

[Ashampoo AI Filter *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\AI Filter #*
FileKey1=%UserProfile%\AI 1 *|*.log

[Ashampoo ANALOG *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\ANALOG #*
FileKey1=%UserProfile%\Analog *|*.log

[Ashampoo BLACK & WHITE *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\BLACK & WHITE #*
FileKey1=%UserProfile%\BlackWhite *|*.log

[Ashampoo COLOR *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\COLOR #*
FileKey1=%UserProfile%\Color *|*.log

[Ashampoo DENOISE *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\DENOISE #*
FileKey1=%UserProfile%\DeNoise *|*.log

[Ashampoo FOCUS *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\FOCUS #*
FileKey1=%UserProfile%\Focus *|*.log

[Ashampoo Foto 3D *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\Foto3D #*
FileKey1=%UserProfile%\Foto3D *|*.log

[Ashampoo HDR *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\HDR #*
FileKey1=%UserProfile%\HDR *|*.log

[Ashampoo NEAT *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\NEAT #*
FileKey1=%UserProfile%\Neat *|*.log

[Ashampoo SHARPEN *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\SHARPEN #*
FileKey1=%UserProfile%\Sharpen *|*.log
FileKey2=%UserProfile%\SharpenVideo *|*.log

[Ashampoo Snap AutoSaves *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo Snap*
FileKey1=%UserProfile%\Pictures\Ashampoo Snap*\_SNAPDOC|*|RECURSE

[Ashampoo Video Optimizer Pro *]
LangSecRef=3024
DetectFile=%AppData%\Ashampoo\Ashampoo Video Optimizer Pro
FileKey1=%UserProfile%\Documents|Ashampoo Video Optimizer Pro.tmp

[Ashampoo ZOOM *]
LangSecRef=3024
DetectFile=%ProgramFiles%\Ashampoo\Ashampoo App\products\ZOOM #*
FileKey1=%UserProfile%\Documents\Zoom *|*.log

[Athentech Perfectly Clear *]
LangSecRef=3021
Detect=HKLM\Software\Athentech
FileKey1=%LocalAppData%\cache\Athentech|*|REMOVESELF
