; L.ini (c) 2026 Hazel Ward
;
; This file is part of a collection of winapp2ool ini files that are used to generate winapp2.ini
; and thus is not intended to be used standalone or with any cleaning software
;
; Most entries in these files are incomplete and may not function as expected if used on their own
;
; This file is one of 27 alphabetically-split source files used by winapp2ool's EntryBuilder module
; At runtime, all 27 source files are combined in-memory and processed alongside the shared
; scaffold catalogs at ..\Scaffolds\*.ini to generate winapp2.ini entries
;
; This file contains entries for applications whose names begin with the letter L
;
; See the EntryBuilder readme for documentation on EntryBuilder's shorthand-DSL key syntax: https://github.com/MoscaDotTo/Winapp2/blob/master/winapp2ool/modules/entrybuilder/readme.md
