; M.ini (c) 2026 Hazel Ward
;
; This file is part of a collection of winapp2ool ini files that are used to generate winapp2.ini
; and thus is not intended to be used standalone or with any cleaning software
;
; Most entries in these files are incomplete and may not function as expected if used on their own
;
; This file is one of 27 alphabetically-split source files used by winapp2ool's EntryBuilder module
; At runtime, all 27 source files are combined in-memory and processed alongside the shared
; scaffold catalogs at ..\Scaffolds\*.ini to generate winapp2.ini entries
;
; This file contains entries for applications whose names begin with the letter M
;
; See the EntryBuilder readme for documentation on EntryBuilder's shorthand-DSL key syntax: https://github.com/MoscaDotTo/Winapp2/blob/master/winapp2ool/modules/entrybuilder/readme.md

[Microsoft Outlook *]
VersionNum=9.0,10.0,11.0,12.0,14.0,15.0,16.0
MRUNum=1,2,3
LangSecRef=3022

Detect=HKCU\Software\Microsoft\Office\<VersionNum>\Outlook
RegKeyBase=HKCU\Software\Microsoft\Office\<VersionNum>\Outlook\Office Finder|<MRUNum>
RegKeyBase=HKCU\Software\Microsoft\Office\<VersionNum>\Outlook\Preferences|LocationMRU
RegKeyBase=HKCU\Software\Microsoft\Office\<VersionNum>\Outlook\Profiles\Outlook\0a0d020000000000c000000000000046|101f0445
RegKey=HKCU\Identities\{9745A9A1-95D3-4584-B4E8-C9C2374B3BD3}\Software\Microsoft\Outlook Express\5.0\Recent Stationery List
RegKey=HKCU\Software\Microsoft\Office\16.0\Outlook\Diagnostics\BootDiagnosticsData|BootDiagnosticsLogFile

[Microsoft Outlook For Windows *]
Root=%LocalAppData%\Microsoft\Olk
WebViewRoot=<Root>\EBWebView
WebViewScaffolds=All
ExcludeWebViewScaffolds=WebStorage
LangSecRef=3022

FileKeyBase=<Root>\<Logs,Application\SetupMetrics>|*|REMOVESELF
FileKeyBase=<Root>\Application|debug.log
