; Y.ini (c) 2026 Hazel Ward
;
; This file is part of a collection of winapp2ool ini files that are used to generate winapp2.ini
; and thus is not intended to be used standalone or with any cleaning software
;
; Most entries in these files are incomplete and may not function as expected if used on their own
;
; This file is one of 27 alphabetically-split source files used by winapp2ool's EntryBuilder module
; At runtime, all 27 source files are combined in-memory and processed alongside the shared
; scaffold catalogs at ..\Scaffolds\*.ini to generate winapp2.ini entries
;
; This file contains entries for applications whose names begin with the letter Y
;
; See the EntryBuilder readme for documentation on EntryBuilder's shorthand-DSL key syntax: https://github.com/MoscaDotTo/Winapp2/blob/master/winapp2ool/modules/entrybuilder/readme.md
; Any contributions are appreciated. Please refer to our contributor guidelines to learn to make your own entries here: https://github.com/MoscaDotTo/Winapp2/blob/master/CONTRIBUTING.md
; Winapp2.ini is fully licensed under the CC-BY-SA-4.0 license agreement. Please refer to our license agreement before using Winapp2.ini: https://github.com/MoscaDotTo/Winapp2/blob/master/License.md
; You may copy, modify, remix, share, show, and transmit Winapp2 but you must redistribute under the same license and you must attribute the original work to the winapp2 project

[YACReader *]
LangSecRef=3021
DetectFile=%LocalAppData%\YACReader\YACReader*
FileKey1=%LocalAppData%\YACReader\YACReader*|yacreader*.log

[YouTube-DL *]
LangSecRef=3024
DetectFile=%UserProfile%\.cache\youtube-dl
FileKey1=%UserProfile%\.cache\youtube-dl|*|RECURSE

[YouTubeByClick *]
LangSecRef=3022
DetectFile=%AppData%\YouTubeByClick
FileKey1=%AppData%\YouTubeByClick|History.ytb

[yWriter *]
LangSecRef=3021
DetectFile=%AppData%\Spacejock Software\yWriter*
FileKey1=%AppData%\Spacejock Software\yWriter*|Log.txt
FileKey2=%UserProfile%\Documents\Logs|*.txt
FileKey3=%UserProfile%\Documents\ywriter projects\*ywriter\Logs|*
FileKey4=%UserProfile%\Documents\ywriter projects\*ywriter\ywtemp|*
